### ISSUE TITLE
Nanobox server not running

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#427]
Currently launching Nanobox in a CI environment (thus using the CI bootstrap script) fails:

```
Error   : nanobox-server service start was successful but the service is not running
Context : 
```

Any idea how to get more output for this?

**Comment by lyondhill** [comment]
this happens when a ci does not start services the same way as a native linux machine would. shippable is a testable CI.

**Comment by mbrodala** [comment]
See [this build log](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/9/1/console) for details. And the [repository source](https://bitbucket.org/mbrodala/shippable-nanobox/src).

**Comment by lyondhill** [comment]
So the problem I have found so far is that on shippable instead of running inside a vm like other CI's on shippable runs inside a docker container. then in that container they clone the git repo inside /root/src/<repo>. This creates 2 problems:
1: nanobox is expecting a standard service manager (systemd, upstart, etc). But nanobox cannot start its server
2: Shippable grants access from inside the container to the docker sock file which is good. but nanobox trys to mount the code folder into the docker container ( -v <code folder>:/app) the problem with this is that in shippable they just clone the nanobox code folder inside the container and it doesnt really exist on the host (technically it does exist but under the docker container id) so when the docker server on the host gets the request to mount /root/src/<repo> that folder doesnt exist on the host.

**Comment by mbrodala** [comment]
I'm not that much into Docker yet but do you see a way to have Nanobox' containers directly access directories of Shippable's build container? Do you see any other way to solve this?

As for the startup issue I'm not sure if there is anything I can do. Can't the Nanobox server be started in background as regular binary?

**Comment by mbrodala** [comment]
@lyondhill I've created a [Shippable support ticket](https://github.com/Shippable/support/issues/3525), maybe you can watch this ticket and join the discussion once more detailled questions show up.

**Comment by mbrodala** [comment]
Do you have any other ideas how this could be solved given the [options to customize the build](http://docs.shippable.com/ci/shippableyml/)?

**Comment by mbrodala** [comment]
@lyondhill Do you think issue 2 can be fixed as [described here](http://docs.shippable.com/ci/docker-compose/#1-pre_ci_boot)?

```yaml
pre_ci_boot:
  options: "-v /app:/app"
```

> This mounts the directory /app on the host to the /app directory on the container. By copying data/code to the /app directory in the container in a CI task, we make those files available in the /app directory on the host. The /app directory can be replaced by any other directory.

Then later `cp -R . /app`.

**Comment by mbrodala** [comment]
Is there any way to launch the Nanobox server without a service manager?

**Comment by danhunsaker** [comment]
Actually, yes, there is. As root: `nanobox server`

**Comment by mbrodala** [comment]
I just tried that and the process [keeps hanging afterwards](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/18/1/console):

```
nanobox server --trace  

   0.00/10.72MB [                                          0.00%]

   ...

   10.72/10.72MB [****************************************  100.00%]
2017/06/13 07:12:52 <nil>
```

I guess there is no forking into background if the server is started this way? But I also cannot simply do a `nanobox server &` to start it in the background since then the following Nanobox commands wouldn't work as long as the server is not yet started (which takes a considerable amount of time). And `wait`ing for the background process also wouldn't help since it never finishes (or shouldn't) unless it's an error what I'm seeing here.

Any idea how to get this working?

**Comment by danhunsaker** [comment]
Looks like it's actually trying to run `nanobox-update` first thing. Maybe run that manually ahead of time? Once that closes, you should be able to start the server in the background just fine, I believe.

**Comment by mbrodala** [comment]
That [didn't work out well](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/19/1/console) and yes, the issue is obvious:

```
nanobox-update --trace  
/root/a52197e6-7908-4ce6-a7ef-3f5c1ee0273e.sh: line 73: nanobox-update: command not found
```

I'll try to manually download this binary.

**Comment by mbrodala** [comment]
After loading the `nanobox-update` binary and making it executable the behavior is unchanged except that apparently the update is now performed twice. Again, `nanobox server` [hangs at the end](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/21/1/console):

```
nanobox-update --trace 

   0.00/15.10MB [                                          0.00%]

   ...

   15.10/15.10MB [****************************************  100.00%]

nanobox server --trace

   0.00/10.72MB [                                          0.00%]

   ...

   10.72/10.72MB [****************************************  100.00%]
2017/06/13 10:36:15 <nil>
```

**Comment by danhunsaker** [comment]
Interesting size difference, there, too...

As to hanging at the end, that would be the server actually running. I'm not sure what it's actually downloading, at this point, though, or why. One of the staff members will have to weigh in to get much further.

**Comment by mbrodala** [comment]
Alright, I hope a staff member chimes in then. Thanks so far.

**Comment by mbrodala** [comment]
As [mentioned here](https://github.com/Shippable/support/issues/3525#issuecomment-307704728) it should be possible to basically add another volume mount to the Shippable build container, copy everything into that directory and thus make it accessible on the host. If another container then volume mounts that directory, it should be able to access the code.

**Comment by mbrodala** [comment]
I've now asked Shippable if they could implement a feature to completely [override the build container command](https://github.com/Shippable/support/issues/3688) (currently `docker run`). This way I should be able to use Nanobox to run the build itself.

**Comment by mbrodala** [comment]
Currently I'm trying to install Nanobox on the Shippable build host instead and mount it into the build container. However currently [this fails](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/32/summary/console):

```
# bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                     
            Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 15.0M  100 15.0M    0     0  60.7M      0 --:--:-- --:--:-- --:--:-- 60.8M
--------------------------------------------------------------------------------
+ ERROR:
+ Nanobox is designed to run as a standard user (non root)
+ Please run all nanobox commands as a non privilage user
--------------------------------------------------------------------------------
Nanobox is ready to go!

# nanobox version
Using nanobox with docker-machine requires tools that appear to not be available on your system.
vboxmanage
View these requirements at docs.nanobox.io/install/requirements/docker-machine/
```

There are various issues:

1. Running Nanobox as `root` should be allowed on CI systems.
2. The bootstrap script happily continues even if an error occurs in the middle, it should stop and fail hard instead.

**Comment by danhunsaker** [comment]
It should be working as root in CI mode. Wonder if the CI bootstrap sets CI mode first or not. It'll have to do that before anything else.

I think that's part of why it's trying to use VirtualBox, too.

**Comment by mbrodala** [comment]
Small update: the error is caused by the CI bootstrap script which runs `nanobox config set provider native` before `nanobox config set ci-mode true`. If the latter is the first invocation of Nanobox, that part [works just fine](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/35/summary/console).

**Comment by danhunsaker** [comment]
Indeed. This confirms my suspicion, above.

PR submitted to fix this in nanobox-io/bootstrap#27...

**Comment by mbrodala** [comment]
Thanks to that fix I was able to successfully install Nanobox on the build host machine:

```
build_pre_ci
  bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
  nanobox version
  Nanobox version 2.1.2 (eea68d66ac4e86987e8a15215bd2a06a)
```

However, currently I am unable to properly mount the Nanobox binary into the build container. Neither mounting it as single file ([using `-v ~/../usr/local/bin/nanobox:/usr/local/bin/nanobox`](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/41/summary/console)) nor mounting the whole parent folder ([using `-v /usr/local/bin:/usr/local/bin/host`](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/41/summary/console)) works. The Nanobox binary always appears as directory in the build container ...

**Comment by mbrodala** [comment]
Yesterday I tried the same though a simple test and it worked just fine:

```
$ docker run -it --rm -v $(which nanobox):/usr/local/bin/nanobox php bash
# ls -l /usr/local/bin/
total 38764
-rwxrwxr-x 1 root root       118 Jul  3 21:22 docker-php-entrypoint
-rwxrwxr-x 1 root root      1276 Jul  3 21:22 docker-php-ext-configure
-rwxrwxr-x 1 root root      2288 Jul  3 21:22 docker-php-ext-enable
-rwxrwxr-x 1 root root      2223 Jul  3 21:22 docker-php-ext-install
-rwxrwxr-x 3 root root       587 Jul  3 21:22 docker-php-source
-rwxr-xr-x 1 root staff 15841242 Jun 15 21:34 nanobox
-rwxr-xr-x 2 root staff      817 Jul  3 21:27 pear
-rwxr-xr-x 2 root staff      838 Jul  3 21:27 peardev
-rwxr-xr-x 2 root staff      754 Jul  3 21:27 pecl
lrwxrwxrwx 1 root staff        9 Jul  3 21:27 phar -> phar.phar
-rwxr-xr-x 2 root staff    14829 Jul  3 21:27 phar.phar
-rwxr-xr-x 2 root staff 11828056 Jul  3 21:27 php
-rwxr-xr-x 2 root staff     2620 Jul  3 21:27 php-config
-rwxr-xr-x 2 root staff 11959520 Jul  3 21:27 phpdbg
-rwxr-xr-x 2 root staff     4547 Jul  3 21:27 phpize
# nanobox

CONFIGURE NANOBOX
---------------------------------------------------------------
Please answer the following questions so we can customize your
nanobox configuration. Feel free to update your config at any
time by running: 'nanobox configure'

(Learn more at : https://docs.nanobox.io/local-config/configure-nanobox/)

How would you like to run nanobox?
  a) Inside a lightweight VM
  b) Via Docker Native

  Note : Mac users, we strongly recommend choosing (a) until Docker Native
         resolves an issue causing slow speeds : http://bit.ly/2jYFfWQ

Answer: ^C
```

Since this [still does not work](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/43/summary/console) on Shippable, I'll ask over there.

**Comment by mbrodala** [comment]
See https://github.com/Shippable/support/issues/3707

**Comment by mbrodala** [comment]
That didn't work out. In the end I managed to get the Nanobox CLI to exist on the build host but that didn't make a difference.

**Comment by mbrodala** [comment]
BTW I also just tried CircleCI [but again](https://github.com/nanobox-io/nanobox/issues/427#issuecomment-308031162), [server startup fails](https://circleci.com/bb/mbrodala/shippable-nanobox/6):

```
sudo nanobox server


   0.48/10.73MB [*                                         4.48%]   1.46/10.73MB [*****                               2.41/10.73MB [********        2.89/10.73MB [**********                                 3.37/10.73   3.85/10.73MB [**************            4.33/10.73MB [****************                          40.36%]
   4.81/10.73MB [******   5.28/10.73MB [*******************                 5.7   6.24/10.73MB [****************   6.72/10.73MB [*************************                 6   7.20/10.73MB    7.69/10.73MB [**************************   8.63/10.73MB [*********   9.11/10.73MB [*********************************      9.59/1   10.07/10.73MB [*      10.73/10.73MB [****************************************  100.00%]
2017/07/11 07:56:57 <nil>
```

**Comment by mbrodala** [comment]
@pablorsk Thanks for checking, that was on my TODO list but now I am sure that it won't ever work either.

**Comment by seanculver** [comment]
@mbrodala I've successfully ran CI with circleci using my nanobox thanks to using this Gist from @brandoncc - https://gist.github.com/brandoncc/e680d39490c434b059486fa08fc089c6

Here is my elixir version of the same thing and even has an auto deploy workflow built in.
https://gist.github.com/seanculver/91bd62f31e2feec589e0f91644caf0df

I haven't figured out caching of the box yet but I'll update my gist with the caching stuff, it added a few minutes to my build but I'll see if I can't get it back to where it was.

Hope this helps!

What Brandon said was it might be the `machine: true` flag that kicks it out of a docker container and allows us to run our own docker container via nanobox, this is just a hunch though.

**Comment by mbrodala** [comment]
@seanculver Thanks a lot for the hints. I can confirm that this setup is [working fine|https://circleci.com/gh/mbrodala/nanobox-circleci]. I'll look forward to even faster builds once caching is working. :-)

**Comment by brandoncc** [comment]
@seanculver @mbrodala I'm glad my config worked for you guys. Just an FYI, there may be an additional charge for using `machine: true` in the future, since it gives you direct OS access on a powerful VM. You can see more [here](https://circleci.com/docs/2.0/executor-types/#using-machine). At the bottom of that section you will notice that there is also a `docker_layer_caching` config option, which may handle the caching properly (it may not cache nanobox properly, I don't know for sure). Unfortunately, it is a paid addon.

**Comment by pablorsk** [comment]
On Bitbucket Pipelines receive new errors:

```bash
+ nanobox deploy apicultor-20
Failed to get D-Bus connection: Unknown error -1
Failed to get D-Bus connection: Unknown error -1
Failed to get D-Bus connection: Unknown error -1
Error   : nanobox-server service start was successful but the service is not running
Context : 
```

And this is my bitbucket-pipelines.yml
```yaml

## WARNING!!!
## DONT WORK YET

image: susa4ostec/bitbucket-pipelines-php7.1-mysql

options:
  docker: true

pipelines:
    default:
        - step:
            name: Install dependecies and test
            caches:
                - composer
            script:
                - apt-get update -q
                - sh some script.sh
    branches:
        master:
            - step:
                name: Publish to staging version
                deployment: staging
                caches:
                    - composer
                script:
                    - sh -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
                    - nanobox deploy apicultor-20
```

**Comment by arnaud-zg** [comment]
Any news on this problem? I have the same issue on Gitlab Pipelines.

**Comment by brandoncc** [comment]
If it helps anyone, I use this for circleci: https://gist.github.com/brandoncc/e680d39490c434b059486fa08fc089c6

The downside is it can't cache so it takes while to setup the docker image. A full test run takes about 15 minutes.
